### ISSUE TITLE
default config is not spinning up

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [zokradonh/kopano-docker#58]
What i did:

1. clone the repo
2. executed setup.sh with all default values
3. comment web service in docker-compose.yml, because i have already a running reverse proxy
4. spin-up all services with docker-compose up -d

What happens (some services exits):
```
3f3c8d0d3eb        zokradonh/kopano_core:latest             "/usr/bin/dumb-init …"   28 minutes ago      Exited (1) 28 minutes ago                                                                                        kopano_gateway
15d707b4655c        zokradonh/kopano_zpush:latest            "/usr/bin/dumb-init …"   28 minutes ago      Up 28 minutes               80/tcp                                                                               kopano_zpush
feb2a2bf1824        zokradonh/kopano_core:latest             "/usr/bin/dumb-init …"   28 minutes ago      Up 28 minutes (unhealthy)                                                                                        kopano_dagent
be29da4fc93b        zokradonh/kopano_core:latest             "/usr/bin/dumb-init …"   28 minutes ago      Exited (0) 27 minutes ago                                                                                        kopano_search
88397b1e3474        zokradonh/kopano_core:latest             "/usr/bin/dumb-init …"   28 minutes ago      Up 28 minutes (unhealthy)                                                                                        kopano_ical
6815212180af        zokradonh/kopano_core:latest             "/usr/bin/dumb-init …"   28 minutes ago      Up 28 minutes (unhealthy)                                                                                        kopano_spooler
3f95b484f7e8        zokradonh/kopano_webapp:latest           "/usr/bin/dumb-init …"   28 minutes ago      Up 28 minutes               80/tcp                                                                               kopano_webapp
6a8f244db4a5        zokradonh/kopano_core:latest             "/usr/bin/dumb-init …"   28 minutes ago      Up 28 minutes (unhealthy)                                                                                        kopano_monitor
df86cc16b22d        zokradonh/kopano_core:latest             "/usr/bin/dumb-init …"   28 minutes ago      Up 28 minutes (unhealthy)                                                                                        kopano_server
c4a26e014328        tvial/docker-mailserver:release-v6.1.0   "/bin/sh -c 'supervi…"   28 minutes ago      Up 28 minutes               110/tcp, 143/tcp, 465/tcp, 587/tcp, 993/tcp, 995/tcp, 0.0.0.0:25->25/tcp, 4190/tcp   mail
8efcfc046407        osixia/phpldapadmin:0.7.2                "/container/tool/run…"   28 minutes ago      Up 28 minutes               80/tcp, 443/tcp                                                                      ldap-admin
52f00be0677e        zokradonh/kopano_ssl                     "/start.sh"              28 minutes ago      Exited (0) 28 minutes ago                                                                                        kopano_ssl
a433538a8f3a        zokradonh/kopano_ldap_demo               "/container/tool/run…"   28 minutes ago      Up 28 minutes               0.0.0.0:389->389/tcp, 636/tcp                                                        ldap
66a748029c9b        mariadb:10.3.10-bionic                   "docker-entrypoint.s…"   28 minutes ago      Up 28 minutes (healthy)     3306/tcp                                                                             kopano_db
```

kopano_gateway exited with:
```2018/12/17 16:30:42 Waiting for: tcp://kopano_server:236
2018/12/17 16:30:42 Problem with dial: dial tcp 192.168.160.5:236: connect: connection refused. Sleeping 1s
2018/12/17 16:30:43 Problem with dial: dial tcp 192.168.160.5:236: connect: connection refused. Sleeping 1s
2018/12/17 16:30:44 Problem with dial: dial tcp 192.168.160.5:236: connect: connection refused. Sleeping 1s
2018/12/17 16:30:45 Problem with dial: dial tcp 192.168.160.5:236: connect: connection refused. Sleeping 1s
2018/12/17 16:30:46 Problem with dial: dial tcp 192.168.160.5:236: connect: connection refused. Sleeping 1s
2018/12/17 16:30:47 Problem with dial: dial tcp 192.168.160.5:236: connect: connection refused. Sleeping 1s
2018/12/17 16:30:48 Problem with dial: dial tcp 192.168.160.5:236: connect: connection refused. Sleeping 1s
2018/12/17 16:30:49 Problem with dial: dial tcp 192.168.160.5:236: connect: connection refused. Sleeping 1s
2018/12/17 16:30:50 Problem with dial: dial tcp 192.168.160.5:236: connect: connection refused. Sleeping 1s
2018/12/17 16:30:51 Problem with dial: dial tcp 192.168.160.5:236: connect: connection refused. Sleeping 1s
2018/12/17 16:30:52 Connected to tcp://kopano_server:236
Mon Dec 17 16:30:53 2018: [kopano-gateway|T6] [=======] Starting kopano-gateway version 8.7.80 (pid 6 uid 0)
Mon Dec 17 16:30:53 2018: [kopano-gateway|T6] [error  ] ECChannel::HrSetCtx(): cannot open key file
Mon Dec 17 16:30:53 2018: [kopano-gateway|T6] [error  ] Error loading SSL context, POP3S and IMAPS will be disabled
Mon Dec 17 16:30:53 2018: [kopano-gateway|T6] [crit   ] POP3, POP3S, IMAP and IMAPS are all four disabled
/usr/sbin/kopano-gateway: Startup failed: call failed (80004005). Please check the logfile (-) for details.
```

kopano_search exited with:
```
Dec 17 16:30:41 Configure core service 'search'
Dec 17 16:30:42 Set ownership
2018/12/17 16:30:42 Waiting for: file://var/run/kopano/server.sock
2018/12/17 16:30:52 File file://var/run/kopano/server.sock had been generated
2018-12-17 16:30:54,275 - search - INFO - starting search
2018-12-17 16:30:54,639 - search - INFO - starting initial sync
2018-12-17 16:30:55,318 - search - INFO - stopping search
2018-12-17 16:30:55,327 - search - ERROR - Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kopano/log.py", line 103, in log_exc
    try: yield
  File "/usr/lib/python3/dist-packages/kopano/service.py", line 180, in start
    _daemonize(self.main, options=self.options, log=self.log, config=self.config, service=self)
  File "/usr/lib/python3/dist-packages/kopano/service.py", line 113, in _daemonize
    _daemon_helper(func, service, log)
  File "/usr/lib/python3/dist-packages/kopano/service.py", line 59, in _daemon_helper
    func()
  File "/usr/lib/python3/dist-packages/kopano_search/__init__.py", line 357, in main
    self.initial_sync(self.server.stores())
  File "/usr/lib/python3/dist-packages/kopano_search/__init__.py", line 369, in initial_sync
    folders = [(f.count, s.guid, f.entryid, reindex) for s in stores for f in s.folders()]
  File "/usr/lib/python3/dist-packages/kopano_search/__init__.py", line 369, in <listcomp>
    folders = [(f.count, s.guid, f.entryid, reindex) for s in stores for f in s.folders()]
  File "/usr/lib/python3/dist-packages/kopano/store.py", line 423, in folders
    for folder in self.subtree.folders(recurse=recurse, **kwargs):
  File "/usr/lib/python3/dist-packages/kopano/folder.py", line 682, in folders
    mapitable = self.mapiobj.GetHierarchyTable(flags)
AttributeError: 'NoneType' object has no attribute 'GetHierarchyTable
```

kopano_ssl exited with:

```
Creating CA and Server certificates...
-rw-r--r--    1 root     root          1338 Dec 17 15:30 /kopano/ssl/ca.pem
-rw-r--r--    1 root     root          3017 Dec 17 15:30 /kopano/ssl/kdagent.pem
-rw-r--r--    1 root     root          3017 Dec 17 15:30 /kopano/ssl/kmonitor.pem
-rw-r--r--    1 root     root          3013 Dec 17 15:30 /kopano/ssl/ksearch.pem
-rw-r--r--    1 root     root          3013 Dec 17 15:30 /kopano/ssl/kserver.pem
-rw-r--r--    1 root     root          3013 Dec 17 15:30 /kopano/ssl/kspooler.pem
-rw-r--r--    1 root     root          3013 Dec 17 15:30 /kopano/ssl/kwebapp.
```

**Comment by fbartels** [comment]
Hi @cguentherTUChemnitz,

I am afraid you'd have to provide some more details. 

- e.g. output of `docker-compose ps`
- `docker-compose logs $nameoffailedcontainer`
- ...

**Comment by cguentherTUChemnitz** [comment]
> Hi @cguentherTUChemnitz,
> 
> I am afraid you'd have to provide some more details.
> 
> * e.g. output of `docker-compose ps`
> * `docker-compose logs $nameoffailedcontainer`
> * ...

Sure, i just hit the enter button too early ;)

**Comment by fbartels** [comment]
Ah, that is already way more useful.

> kopano_ssl exited with:

That is normal. The container is only used to create the ssl certificates for the other containers.

> kopano_search exited with:

that looks more like a bug in kopano-search, than in the Docker container. The containers use packages from the nightly builds, so errors in the packages will happen.

> kopano_gateway exited with:

that one is actually a configuration mistake somewhere in the docker containers. I have not yet looked into the why this pops up. I would expect wrong permissions on the file.

**Comment by fbartels** [comment]
ah, yes of course: https://github.com/zokradonh/kopano-docker/blob/master/docker-compose.yml-example#L257-L258

**Comment by fbartels** [comment]
I have disabled the ssl bits for gateway for now, which will result in a successful start.
